// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIpBI1NqLJZ4-YkOU2XcYZjxWsvFNNPcM',
    appId: '1:499262587119:web:b47fab1356d336f09adb1a',
    messagingSenderId: '499262587119',
    projectId: 'deadzone-guard',
    authDomain: 'deadzone-guard.firebaseapp.com',
    storageBucket: 'deadzone-guard.firebasestorage.app',
    measurementId: 'G-MY42CPJDZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAopECCyZXEaWJC_SzCybK9-NyJ10d8F3U',
    appId: '1:499262587119:android:510c6577d167595a9adb1a',
    messagingSenderId: '499262587119',
    projectId: 'deadzone-guard',
    storageBucket: 'deadzone-guard.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzeZYUC5mxOBVJ2J6GsgDiRNLfDWspdVY',
    appId: '1:499262587119:ios:b0f00bd16fc4a5379adb1a',
    messagingSenderId: '499262587119',
    projectId: 'deadzone-guard',
    storageBucket: 'deadzone-guard.firebasestorage.app',
    iosBundleId: 'com.example.deadzoneGuard',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzeZYUC5mxOBVJ2J6GsgDiRNLfDWspdVY',
    appId: '1:499262587119:ios:b0f00bd16fc4a5379adb1a',
    messagingSenderId: '499262587119',
    projectId: 'deadzone-guard',
    storageBucket: 'deadzone-guard.firebasestorage.app',
    iosBundleId: 'com.example.deadzoneGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIpBI1NqLJZ4-YkOU2XcYZjxWsvFNNPcM',
    appId: '1:499262587119:web:5f0940524d71c9809adb1a',
    messagingSenderId: '499262587119',
    projectId: 'deadzone-guard',
    authDomain: 'deadzone-guard.firebaseapp.com',
    storageBucket: 'deadzone-guard.firebasestorage.app',
    measurementId: 'G-TDQLTYM87G',
  );
}
